### ISSUE TITLE
Can not run it in Console, help me pls

### ISSUE THREAD

**Issue by linquocte** [N-X-T/Download-All-Video-User-Douyin#1]
<img width="610" alt="image" src="https://user-images.githubusercontent.com/89297828/216827776-47370c0e-a853-4f57-879f-72b61e09ea2d.png">

**Comment by N-X-T** [comment]
Douyin had some updates! I'll let you know when the bug is fixed.

**Comment by N-X-T** [comment]
I fixed the bug. Try again and let me know if you get any errors!

**Comment by linquocte** [comment]
> I fixed the bug. Try again and let me know if you get any errors!

I have try 1 profile first, it download okey, but this profile have about 200 videos so when i have download 40 video, it was stop, no response anymore. Then, i try the second profile, still get red alert in the console, this profile have 60 videos, after download 10 videos, it  still stop and not response anymore, i think the code is not really complete, can you fix it again. Thank a lot, brother

<img width="514" alt="image" src="https://user-images.githubusercontent.com/89297828/217593770-f68e6ee4-a2d1-4ba5-84b9-b265d2ca965b.png">

**Comment by N-X-T** [comment]
I think the download is blocked because there are too many downloads at once. I added a delay for each video download. Hope it works! :v
More delay, edit `await waitforme(1000);`, time in milisecond

**Comment by linquocte** [comment]
i have just check the code today, it 's bug in line 86

**Comment by N-X-T** [comment]
> i have just check the code today, it 's bug in line 86

sorry, it stupid error :)) i fixed it!
